version: '3.9'

services:
  app:
    image: emper/cms
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres?sslmode=disable
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    networks:
      - app-net
    depends_on:
      - postgres

  postgres:
    container_name: database
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-net
    ports:
      - '5432:5432'
    env_file:
      - ./.env.pgsql

###############################################################################
# FIM DOS SERVICES
###############################################################################

networks:
  app-net:
    name: external-networks
